# Generated by Django 2.0.6 on 2019-10-03 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazaarapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrole',
            old_name='roleid',
            new_name='roleId',
        ),
    ]
