# Generated by Django 2.0.6 on 2019-10-03 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazaarapp', '0002_auto_20191003_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrole',
            old_name='roleId',
            new_name='roleid',
        ),
    ]
