# Generated by Django 2.0.6 on 2019-10-03 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bazaarapp', '0003_auto_20191003_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSignup',
            fields=[
                ('userName', models.CharField(default='', max_length=200)),
                ('userEmail', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('userMobile', models.CharField(default='', max_length=10)),
                ('userPassword', models.CharField(default='', max_length=200)),
                ('userAddress', models.CharField(default='', max_length=200)),
                ('userCity', models.CharField(default='', max_length=200)),
                ('userGender', models.CharField(default='', max_length=10)),
                ('userPinCode', models.CharField(default='', max_length=200)),
                ('userDob', models.CharField(default='', max_length=200)),
                ('userState', models.CharField(default='', max_length=200)),
                ('isActive', models.BooleanField(default=True)),
                ('isAvailable', models.BooleanField(default=True)),
                ('isQueue', models.BooleanField(default=False)),
                ('isVerified', models.BooleanField(default=False)),
                ('roleid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaarapp.UserRole')),
            ],
        ),
    ]
