# Generated by Django 2.0.6 on 2019-10-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaarapp', '0004_usersignup'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='userConfirmationLink',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='userOtp',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='userOtpTime',
            field=models.CharField(default='', max_length=200),
        ),
    ]
