# Generated by Django 2.0.6 on 2019-10-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaarapp', '0005_auto_20191004_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='userToken',
            field=models.CharField(default='', max_length=200),
        ),
    ]
