# Generated by Django 2.0.6 on 2019-10-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaarapp', '0006_usersignup_usertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='userProfile',
            field=models.CharField(default='', max_length=255),
        ),
    ]
