# Generated by Django 2.0.6 on 2019-10-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaarapp', '0007_usersignup_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginRecord',
            fields=[
                ('logid', models.AutoField(primary_key=True, serialize=False)),
                ('loginTime', models.CharField(default='', max_length=255, null=True)),
                ('logoutTime', models.CharField(default='', max_length=255, null=True)),
                ('userEmail', models.CharField(default='', max_length=255, null=True)),
                ('ipAddress', models.CharField(default='', max_length=255, null=True)),
                ('macAddress', models.CharField(default='', max_length=255, null=True)),
            ],
        ),
    ]
