# Generated by Django 2.0.6 on 2019-10-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaarapp', '0008_loginrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='shopAadhar',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='shopAadharImage',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='shopAddress',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='shopGst',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='shopPan',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='shopPanImage',
            field=models.CharField(default='', max_length=255),
        ),
    ]
