# Generated by Django 2.0.6 on 2019-10-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsCategories',
            fields=[
                ('categories_id', models.AutoField(primary_key=True, serialize=False)),
                ('categories_Name', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
