# Generated by Django 2.0.6 on 2019-10-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsBrand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_Name', models.CharField(default='', max_length=250, unique=True)),
                ('brand_isActive', models.BooleanField(default='True')),
            ],
        ),
        migrations.RenameField(
            model_name='productstype',
            old_name='type_name',
            new_name='type_Name',
        ),
    ]
