# Generated by Django 2.0.6 on 2019-10-14 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bazaarapp', '0006_usersignup_usertoken'),
        ('managerapp', '0002_auto_20191012_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.CharField(default='', max_length=255, null=True)),
                ('product_size', models.CharField(default='', max_length=255, null=True)),
                ('product_size2', models.CharField(default='', max_length=255, null=True)),
                ('product_size3', models.CharField(default='', max_length=255, null=True)),
                ('product_size4', models.CharField(default='', max_length=255, null=True)),
                ('product_qty', models.IntegerField(default=0)),
                ('product_price', models.IntegerField(default=0)),
                ('product_image1', models.CharField(default='', max_length=255)),
                ('product_image2', models.CharField(default='', max_length=255, null=True)),
                ('product_image3', models.CharField(default='', max_length=255, null=True)),
                ('product_image4', models.CharField(default='', max_length=255, null=True)),
                ('product_isactive', models.BooleanField(default=True)),
                ('product_creation_date', models.CharField(default='', max_length=255)),
                ('brand', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='managerapp.ProductsBrand')),
                ('productcategory', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='managerapp.ProductsCategories')),
                ('productstype', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='managerapp.ProductsType')),
                ('user_email', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bazaarapp.UserSignup')),
            ],
        ),
    ]
